Array Reshaping--> Reshape,Ravel,Flatten

In [2]:
import numpy as np

In [3]:
#reshape
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [4]:
reshape2=reshaped.reshape(3,2)
print(reshape2)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
# reval-->convert 1D array
ravel=reshaped.ravel()
print(ravel)

[1 2 3 4 5 6]


In [6]:
ravel[0]=100
print(ravel) # it is a view
print(reshaped)

[100   2   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


In [7]:
#  flatten --> convert to 1D array
# returns a copy of the array

flat=reshaped.flatten()
print(flat)



[100   2   3   4   5   6]


In [8]:
flat[1]=10
print(flat)
print(reshaped)

[100  10   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


Arithmetic Operations of Numpy Arrays

In [9]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)  #abbition
print(a-b)  #subtraction
print(a*b)  #multiplication
print(a/b)  #division
print(a//b)  #integer division
print(b//a)
print(a%b)  #modulos (reminder)
print(a**b) #power
print(a**2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[5 3 2 2]
[1 2 3 4]
[    1    64  2187 65536]
[ 1  4  9 16]


Universal functions --> ufuncs

In [10]:
# square root-->np.sqrt()
arr=np.array([1,4,9,16])

print(np.sqrt(arr))

[1. 2. 3. 4.]


In [11]:
# exponentioal-->np.exp()-->e^x-->x is any integer
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [12]:
# sin function -->np.sin()
angles=np.array([0,np.pi,np.pi/2,180])
print(np.sin(angles))

[ 0.00000000e+00  1.22464680e-16  1.00000000e+00 -8.01152636e-01]


Indexing and slicing

In [13]:
# indexing
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[-4]) #negative indexing

1
2


In [14]:
# slicing
arr=np.array([1,2,3,4,5,7])
print(arr[1:4]) #last index not included
print(arr[0:6:2]) #start,end,step
print(arr[-1:-4:-1])
print(arr[::-1]) #reverse
print(arr[::2])
print(arr[-1:-4])


[2 3 4]
[1 3 5]
[7 5 4]
[7 5 4 3 2 1]
[1 3 5]
[]


Multi dimensional slicing

In [15]:
matrix=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
# two get first 2rows completely
print(matrix[0:2,:]) 
print(matrix[1:2,1:2])
print(matrix[0:2,0:2])
print(matrix[1:,1:])

[[1 2 3]
 [4 5 6]]
[[5]]
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [16]:
# np.take--> built in function to perforam indexing anf slicing
arr=np.array([1,2,3,4,5])
ind=[0,4]
print(np.take(arr,ind))

[1 5]


iterating with nditer()

In [17]:
arr=np.array([[1,2,3],[4,5,6]])
for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 4 5 6 

In [18]:
# ndenumerate()-->both index+value
for ind,x in np.ndenumerate(arr):
    print(ind,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


Views vs copy

In [19]:
# view
arr=np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [20]:
view[0]=100
view

array([100,   3])

In [21]:
arr

array([  1, 100,   3,   4,   5])

In [22]:
# copy--> original array remains same
arr=np.array([1,2,3,4,5])
copy=arr[1:3].copy()
print(copy)

copy[0]=100
print(copy)
print(arr)

[2 3]
[100   3]
[1 2 3 4 5]


Transpose of matrix


In [23]:

arr=np.array([[1,2],[3,4]])
print(arr)
print(arr.transpose())

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


Swapaxes

In [24]:
# swapaxes-->swap 2 specific axes in a matrix
arr=np.array([[[1,2],[1,2]]])
arr.shape

(1, 2, 2)

In [25]:
swap=np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

Concatenation

In [32]:
a=np.array([1,2,3])
b=np.array([4,5,6])
combine= np.concatenate((a,b))
print(combine)

[1 2 3 4 5 6]


In [ ]:
# np.vstack()--> it gives vertival stack
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[4,5,6],[8,9,0]])

print(np.vstack((a,b)))

[[1 2 3]
 [5 6 7]
 [4 5 6]
 [8 9 0]]


In [28]:
# np.hstack()--> it gives horixontal stack
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[4,5,6],[8,9,0]])

print(np.hstack((a,b)))

[[1 2 3 4 5 6]
 [5 6 7 8 9 0]]


In [ ]:
# np.stack()--> it takes (a,b), axis=0 row wise axis=1 colm wise
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[4,5,6],[8,9,0]])

print(np.stack((a,b),axis=0)) #row wise

print(np.stack((a,b),axis=1)) #col wise

[[[1 2 3]
  [5 6 7]]

 [[4 5 6]
  [8 9 0]]]
[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 0]]]


Splitting Arrays


In [33]:
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
# to split into two equal parts
print(np.split(arr,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [35]:
print(np.hsplit(arr,2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [36]:
print(np.vsplit(arr,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
