Array Reshaping--> Reshape,Ravel,Flatten

In [2]:
import numpy as np

In [6]:
#reshape
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [7]:
reshape2=reshaped.reshape(3,2)
print(reshape2)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
# reval-->convert 1D array
ravel=reshaped.ravel()
print(ravel)

[1 2 3 4 5 6]


In [ ]:
ravel[0]=100
print(ravel) # it is a view
print(reshaped)

[100   2   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


In [11]:
#  flatten --> convert to 1D array
# returns a copy of the array

flat=reshaped.flatten()
print(flat)



[100   2   3   4   5   6]


In [12]:
flat[1]=10
print(flat)
print(reshaped)

[100  10   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


Arithmetic Operations of Numpy Arrays