In [1]:
import numpy as np

Repeating

In [3]:
# repeats each elemnt
arr=np.array([1,2,3])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


Tile

In [4]:
# repeate the whole array
print(np.tile(arr,2))

[1 2 3 1 2 3]


Aggregrate Functions --> summerize the entire array

In [ ]:
arr=np.array([1,2,3])

print(np.sum(arr)) # sum of arrays
print(np.mean(arr)) # average of array
print(np.min(arr)) # minimum val
print(np.max(arr)) # max val
print(np.median(arr)) # middle val
print(np.std(arr)) # standard diviation
print(np.var(arr)) #variance --> sq od std

6
2.0
1
3
2.0
0.816496580927726
0.6666666666666666


In [14]:
matrix=np.array([[1,2,3],[4,5,6]])

print(np.sum(matrix,axis=1))

[ 6 15]


Cumulative operations--> running total

In [ ]:
arr=np.array([1,2,3])

print(np.cumsum(arr))
print(np.cumprod(arr)) #product

[1 3 6]
[1 2 6]


Conditional Based choices

In [36]:
# Where

arr=np.array([1,2,3])
print(arr)

result = np.where(arr<=2, "low" , "high")
print(result)

[1 2 3]
['low' 'low' 'high']


In [19]:
# argwhere: row-column positions for 2d array
arr=np.array([10,20,40,50,60,12])
print(np.argwhere(arr>30))


[[2]
 [3]
 [4]]


In [28]:
# logical and

mask=np.logical_and(arr>20 , arr<60)
print(mask)
print(arr[mask])

[False False  True  True False False]
[40 50]


In [30]:
# logical or
mask=np.logical_or(arr<20, arr>70)
print(mask)
print(arr[mask])

[ True False False False False  True]
[10 12]


In [32]:
# logical not
mask=np.logical_not(arr>50)
print(mask)

[ True  True  True  True False  True]


In [26]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
print(np.argwhere(matrix>3))

[[1 0]
 [1 1]
 [1 2]]


In [35]:
#  non zeros
arr=np.array([0,2,4,0,5,7,8])
print(np.nonzero(arr))

(array([1, 2, 4, 5, 6]),)
