In [ ]:
import numpy as np #alias--> np

In [5]:
arr=np.array([1,2,3])

In [6]:
# dimensions and shape of an array
arr.ndim

1

In [12]:
arr=np.array(322) # 0 dimension
arr.ndim


0

In [16]:
arr2=np.array([[123],[1456]]) # 2 dimension
arr2.ndim
arr2.shape

(2, 1)

In [ ]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])  #3 dimension
arr3.ndim

3

In [ ]:
# create arrays
range = np.arange(1,10) #last number not included
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range = np.arange(1,10,4) # start stop step
range

array([1, 5, 9])

In [ ]:
# linspace
arr=np.linspace(1,2,5) #start ,stop, number of values
arr

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [33]:
# logarithmic scale array
arr=np.logspace(1,3,3) # 10^1--10^3 need 3 points
arr

array([  10.,  100., 1000.])

In [34]:
# np.zeros--> array full of zeros
arr= np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [40]:
arr=np.zeros([3,6,2])
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [42]:
#  create 1's array
arr=np.ones(7,dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1])

In [43]:
# creating an array full of any values
arr=np.full(10,5)
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [44]:
arr=np.full([2,4],5)
arr

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [56]:
# uninitialized array
arr5=np.empty([2,1])
arr5

array([[6.077e-322],
       [7.194e-321]])