In [2]:
import numpy as np #alias--> np
import time

In [3]:
a = [1,2,3,4,5,6,7,8,9,10]*1000000

start = time.time()
for i in range(len(a)):
  a[i] = a[i]*2
print("\nTime taken for list:",time.time()-start)


Time taken for list: 0.6339874267578125


In [4]:

a = [1,2,3,4,5,6,7,8,9,10]*1000000
b=np.array(a)
start = time.time()
b = b*2
print("\nTime taken for array:",time.time()-start)


Time taken for array: 0.057875871658325195


In [5]:
arr=np.array([1,2,3])

In [6]:
# dimensions and shape of an array
arr.ndim

1

In [7]:
arr=np.array(322) # 0 dimension
arr.ndim


0

In [8]:
arr2=np.array([[123],[1456]]) # 2 dimension
arr2.ndim
arr2.shape

(2, 1)

In [9]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])  #3 dimension
arr3.ndim

3

In [10]:
# create arrays
range = np.arange(1,10) #last number not included
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
range = np.arange(1,10,4) # start stop step
range

array([1, 5, 9])

In [12]:
# linspace
arr=np.linspace(1,2,5) #start ,stop, number of values
arr

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
# logarithmic scale array
arr=np.logspace(1,3,3) # 10^1--10^3 need 3 points
arr

array([  10.,  100., 1000.])

In [14]:
# np.zeros--> array full of zeros
arr= np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [15]:
arr=np.zeros([3,6,2])
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
#  create 1's array
arr=np.ones(7,dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1])

In [17]:
# creating an array full of any values
arr=np.full(10,5)
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [18]:
arr=np.full([2,4],5)
arr

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [19]:
# uninitialized array
arr5=np.empty([2,1])
arr5

array([[0.],
       [0.]])

In [23]:
# crreating random float values (0 to 1)
arr=np.random.rand(2,3)
arr

array([[0.84620723, 0.15950358, 0.92450514],
       [0.09254267, 0.30547886, 0.73959736]])

In [ ]:
# random floats standard normal distribution
arr=np.random.randn(2,3) # always mean = 0 and standard deviation = 1
arr

array([[ 0.86043089, -0.39635741,  1.61565855],
       [ 1.08272495,  0.67899085,  0.09025544]])

In [26]:
# random integer
arr=np.random.randint(1,10)
arr

2

In [32]:
arr=np.random.randint(1,10,size=(2,3)) # start,stop-->range,sixe/dimension
print(arr)

[[9 7 8]
 [5 8 1]]


Numpy Data Types and Type Casting

In [51]:
arr=np.array([1,2.1,3,4,5])
print(arr)
print(type(arr))
arr.dtype

[1.  2.1 3.  4.  5. ]
<class 'numpy.ndarray'>


dtype('float64')

In [38]:
lst=["string",2.2,4,6]
arr=np.array(lst)
arr

array(['string', '2.2', '4', '6'], dtype='<U32')

In [ ]:
arr=np.array([1,2,3,4,5]) #int data type
print(arr)
arr.dtype

[1 2 3 4 5]


dtype('int64')

In [52]:
arr=np.array([1,2,3.2,4,5]) #float data type
print(arr)
arr.dtype

[1.  2.  3.2 4.  5. ]


dtype('float64')

In [55]:
arr=np.array(["1",2,3.1,4,5]) #str data type 
print(arr)
arr.dtype

['1' '2' '3.1' '4' '5']


dtype('<U32')

In [ ]:
# to convert the int to float array
arr=np.array([1,2,3,4,5],dtype=np.float64)
arr
arr.dtype

dtype('float64')

In [62]:
arr=np.array([1,2.6,3.2,2.2,6],dtype = np.int32)
arr

array([1, 2, 3, 2, 6], dtype=int32)

type casting --> astype()
to convert one data type to other by creating new array 

In [66]:
arr=np.array([1,2,3,4])
print(arr)
arr.dtype

[1 2 3 4]


dtype('int64')

In [67]:
new_arr=arr.astype(np.float64)
print(new_arr)
new_arr.dtype

[1. 2. 3. 4.]


dtype('float64')

type casting errors

In [70]:
arr=np.array(["1","2","hello"])
arr2=arr.astype(np.int64)
arr2

ValueError: invalid literal for int() with base 10: np.str_('hello')

multi dimensional array manually

In [ ]:
arr=np.array([[1,2,3,4],
             [4,3,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize) # size of each element in bytes

[[1 2 3 4]
 [4 3 5 6]]
2
(2, 4)
8
8
